### ISSUE TITLE
 Alephium: Unknown stratum method alph_submitHashrate

### ISSUE THREAD

**Issue by yahorbukhta** [bzminer/bzminer#10]
Miner call strange method `alph_submitHashrate`.

**Comment by bzminer** [comment]
hi @yahorbukhta , we decided on the alephium discord server (a couple devs) that since this was not currently implemented in any of the pools or code at the time, that we would follow the pattern of eth_submitHashrate and use alph_submitHashrate for the miner to send the reported hashrate to the pool
