### ISSUE TITLE
A/R/I/P-P???

### ISSUE THREAD

**Issue by mtmtmt123** [bzminer/bzminer#24]
Can you help me with the p please recieve i my block reward or not?

**Comment by cloudis31** [comment]
Hey @mtmtmt123 , p stands for pending. Originally one of the pools using alphstratum protocol was not responding to solution submission, so I added the p column to show shares that were found but did not get a response from the pool. As far as block reward, bzminer only shows what the pool or node sat is a valid or rejected solution. The full node  from my understanding does not know if you've actually won the block, since network latency can have an impact on whether solutions you find win you the block. The node has to send out your solution across the network to all the other nodes, and if the majority of them agree that your solution won the block, then you receive the rewards. It's possible that other people solo mining and pools find a solution at the same time, so whoever has a faster network and sends their solution to the most nodes first wins the block. So basically, even if you find a solution, it doesn't always mean you win the block.
