### ISSUE TITLE
No mining devices detected!

### ISSUE THREAD

**Issue by kaaus** [bzminer/bzminer#43]
![cmd_roTxeXD9v0](https://user-images.githubusercontent.com/97175725/151684664-1ba538c9-c254-45da-b80e-fb3323bccfd1.png)

Why is this happening? I have a 1050 ti card, I have always mined RVN, FLUX and others without any problems. Is it a dag size issue? First time using this miner

**Comment by bzminer** [comment]
Hey @kaaus , bzminer isn't able to find nvml.dll, which should have been installed in system32 when installing Nvidia drivers, but sometimes apparently it isn't. Often times reinstalling the Nvidia drivers foxes this, otherwise a work around is to go to the Nvidia install directory and find nvml.dll, and copy it to the bzminer directory

**Comment by kaaus** [comment]
Thanks for the answer, the problem is if I install an Nvidia CUDA, after a few hours my hashrate drops by half, my memclock and coreclock drops like nothing is using the GPU. I always have to reinstall an old driver to get it back to normal. is there any solution to do this with my optimized driver installed or install the necessary CUDA without having to replace my driver?

**Comment by bzminer** [comment]
Just reinstall the driver should put nvmll.dll in a place where bzminer can find it, but if it doesn't or you don't want to reinstall the driver, you can search your computer for nvml.dll , which is usually in the Nvidia install folder , and copy it to bzminers folder. I have plans to expand the search in bzminer for that file, just haven't gotten around to it yet

**Comment by kaaus** [comment]
I did that and now I have a new problem. I saw here in the Issues that it could be an error due to overclocking, I undid the entire oc configuration and left everything normal and even then the error remained

![cmd_IqDhZOKorN](https://user-images.githubusercontent.com/97175725/151740860-ae84f3fa-a230-4a75-8b34-20d961968fc5.png)

**Comment by bzminer** [comment]
@kaaus actually, that reminds me, there are two reasons why a gpu is detected as "hung". the first reason is oc like you mentioned, the second issue is that there's a cuda error, which is what you are experiencing. You are getting this cuda error because bzminer only supports drivers that support cuda 11.5 or greater, however for people who don't want to update their nvidia drivers, the cuda_tk version of bzminer exists, so you should use that. the cuda_tk version supports cuda 11.2, which is nvidias 460 driver. anything below 460 (or specifically 460.27.03) won't work with either bzminer version

**Comment by kaaus** [comment]
Now it worked! Thank you so much for your patience and support!
