### ISSUE TITLE
multi_mine_type not working on my FHR

### ISSUE THREAD

**Issue by BitMaci** [bzminer/bzminer#61]
multi_mine_type 0 (parallel) is not accepted by the .bat file, if opened the miner doesn't start mining and close by itself. I also tried multi_mine_type 0 in config.ini but simply it doesn't work since the command dosn't remain saved in the config.ini file, like if it wasn't recognized. Please provide examples on how use multi_mine_type 0 (parallel) option and where write it. Thanks.

**Comment by bzminer** [comment]
@BitMaci i'll try this out, maybe i've got a bug in the parsing of that command. I'll post back here after i get a chance to test it out

**Comment by bzminer** [comment]
it doesn't necessarily solve this particular issue, but i'll be making multi_mine_type 0 by default. apparently people have been able to get up to 60% eth / 60% alph/kaspa using multi_mine_type 0, which is way better than what you'd be able to get with multi_mine_type 1 right now

**Comment by BitMaci** [comment]
Nice, thanks, so I suppose you'll implement it in the next release. It would be nice to dual mine in parallel and not in alternate mode.

**Comment by bzminer** [comment]
@BitMaci i realized i never added this option to the command line, which is why it wasn't working. i've now added it to the command line, as well as made parallel mining default in v8.0.1. Please feel free to close this issue if that works for you!

**Comment by BitMaci** [comment]
@bzminer Thanks for answering and for the new release but parallel mining doesn't work, at least on my FHR card. Hashrate is unstable for both algos, keeps on going up and down. 1st algo -25% and 2nd algo -50/75%.

**Comment by bzminer** [comment]
@BitMaci it sounds like you've got the alternate mining set up (multi_mine_type = 1). probably your config was saved before the last update, because now the default is alternate mining

for parallel mining, it does 5 seconds eth, 15 seconds other algo. the hashrate averaging is done by default over 30 seconds, so since thats not a multiple of 20 seconds, you'll see hashrate jumping. you should change avg_hr_ms to be a multiple of the total mining cycle time of the two algos, so like 40 seconds (avg_hr_ms: 40000)

Otherwise, make sure your config.txt is set to multi_mine_type: 0 for parallel mining. the command line arguments simply update config.txt, which is the source of truth for settings. you can use the -nc command line flag to disable bzminer from writing to the config.txt if you only want to use command line

**Comment by BitMaci** [comment]
@bzminer Well, it's impossible because I saved BzMiner in another folder, so it wasn't using config.ini of the previous version and should be have started in parallel mode, as per default configuration, but it doesn't. Also I'm interested in ETC/KAWP (NOT ETH)+ALPH, not possible with this version. ETC shares results invalid (in previous version ETC did as working) and KAWPOW doesn't start, Bz Miner states that I haven't enough vRam but I have. BzMiner is the only one who gives me those kind of problems, I'll surely wait for a stable and efficient release to support you. For the moment, can't use. Thanks, bye!
