### ISSUE TITLE
9.0.0 API tells that dualmining is...even if only one algo is used.

### ISSUE THREAD

**Issue by tymoteuszrogalewski** [bzminer/bzminer#67]
Linux version.

DATA=`timeout 5 curl -s http://127.0.0.1:4014/status`
echo ${DATA} | jq -r 'try .pools[1].id // null'
...this gaves me null with all prev bzminer versions
But starting with 9.0.0 I got this and because of that our API client thinks that really dual mining is in progress :)
my command line options is:
-a ethash -w 0xXXXXXX.XXX -p stratum+tcp://eu1.ethermine.org:4444

```
{
  "id": 1,
  "algorithm": "kawpow",
  "wallet": "0x0000000000000000000000000000000000000000",
  "url": [
    "stratum+tcp://yourpool:4444",
    "stratum+tcp://yourpool:4444"
  ],
  "username": "rig",
  "lhr_only": false,
  "test": false,
  "test_diff": 1,
  "test_iteration_ms": 15000,
  "max_connection_retries": 0,
  "delay_before_connection_retry": 3000,
  "current_url": "stratum+tcp://yourpool:4444",
  "status": -771801344,
  "message": "",
  "uptime": "0d 0h 0m 0s",
  "uptime_s": 0,
  "epoch": 0,
  "block": 0,
  "difficulty": 0,
  "pending_solutions": 0,
  "valid_solutions": 0,
  "invalid_solutions": 0,
  "rejected_solutions": 0,
  "total_solutions": 0,
  "stale_solutions": 0,
  "average": 0,
  "accepted_avg_seconds": 0,
  "power": 0,
  "hashrate": 0,
  "average_latency": 0
}
```

**Comment by bzminer** [comment]
@tymoteuszrogalewski i just looked and the api didn't change. i know what the problem is though. bzminer can have multiple pool configs which allow for quickly switching between pools/coins per device, so there may be multiple pool_config elements in the status response. the actual pools being mined to are in the "devices" param, where each device has a property called "pool" which is the pool its mining to as an array, so a device mining to just the first pool_config would have a parameter like "pool": [0]

i'm not sure why you didn't have this issue in the previous version of bzminer, but my guess is that its because in the previous version you only have one pool_config maybe?

**Comment by tymoteuszrogalewski** [comment]
I dont use "config file". Just command line options.
Maybe some changed in "generating config" module changed in your code and "starts" generate second pool even if Im not using it:

```
{
  "id": 1,
  "algorithm": "kawpow",
  "wallet": "0x0000000000000000000000000000000000000000",
  "url": [
    "stratum+tcp://yourpool:4444",
    "stratum+tcp://yourpool:4444"
  ],
```

..this tell that kawpow is a second pool with zeroes wallet, etc.....but I just only mine ethash (in this example)

**Comment by tymoteuszrogalewski** [comment]
I found the reason.
For mistake I include in 9.0.0 your default config.txt and thats why JSON gets me "second" data.
Command line options only affect to first algo in config.txt, and second default was not changed :P

Sorry and I close the subject :)
Have a nice day.

**Comment by bzminer** [comment]
Great @tymoteuszrogalewski ! Thanks for getting back!
